[mypy]
python_version = 3.14
warn_unused_configs = True

[mypy-setuptools.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-json.*]
ignore_missing_imports = True

[mypy-netlistx.*]
ignore_missing_imports = True

[mypy-digraphx.*]
ignore_missing_imports = True

[mypy-mywheel.*]
ignore_missing_imports = True

[mypy-physdes.*]
ignore_missing_imports = True
