/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module circle_fsm_32bit_simple_fixed(clk, rst_n, start, k_in, base_sel, result_x, result_y, done, ready);
  reg [31:0] _00_;
  reg [15:0] _01_;
  reg _02_;
  reg [2:0] _03_;
  reg _04_;
  reg [31:0] _05_;
  reg [2:0] _06_;
  reg _07_;
  reg [31:0] _08_;
  reg [31:0] _09_;
  reg _10_;
  reg [2:0] _11_;
  reg [2:0] _12_;
  reg [2:0] _13_;
  reg [2:0] _14_;
  wire _15_;
  wire _16_;
  wire [31:0] _17_;
  wire [31:0] _18_;
  reg [31:0] angle_reg;
  input [1:0] base_sel;
  input clk;
  reg [15:0] cordic_angle;
  wire [31:0] cordic_cos;
  wire cordic_done;
  wire [31:0] cordic_sin;
  reg cordic_start;
  reg [2:0] current_state;
  output done;
  reg done;
  input [31:0] k_in;
  reg [31:0] k_reg;
  reg [2:0] next_state;
  output ready;
  reg ready;
  output [31:0] result_x;
  reg [31:0] result_x;
  output [31:0] result_y;
  reg [31:0] result_y;
  input rst_n;
  input start;
  wire vdc_done;
  wire vdc_ready;
  wire [31:0] vdc_result;
  reg vdc_start;
  assign _15_ = ! rst_n;
  assign _16_ = ! rst_n;
  assign _17_ = vdc_result * 32'd411775;
  assign _18_ = _17_ >> $signed(32'd16);
  cordic_trig_16bit_simple_fixed cordic_inst (
    .angle(cordic_angle),
    .clk(clk),
    .cosine(cordic_cos),
    .done(cordic_done),
    .ready(),
    .rst_n(rst_n),
    .sine(cordic_sin),
    .start(cordic_start)
  );
  vdcorput_fsm_32bit_simple vdc_inst (
    .base_sel(base_sel),
    .clk(clk),
    .done(vdc_done),
    .k_in(k_reg),
    .ready(vdc_ready),
    .result(vdc_result),
    .rst_n(rst_n),
    .start(vdc_start)
  );
  always @* begin
    _03_ = current_state;
    casez (_15_)
      1'h1:
          _03_ = 3'h0;
      default:
          _03_ = next_state;
    endcase
  end
  always @(posedge clk) begin
      current_state <= _03_;
  end
  always @(negedge rst_n) begin
      current_state <= _03_;
  end
  always @* begin
    _06_ = _11_;
    casez (current_state)
      3'h0:
        begin
          _11_ = _12_;
          casez (start)
            1'h1:
              begin
                _12_ = 3'h1;
              end
            default:
                _12_ = current_state;
          endcase
        end
      3'h1:
        begin
          _11_ = 3'h2;
        end
      3'h2:
        begin
          _11_ = _13_;
          casez (vdc_done)
            1'h1:
              begin
                _13_ = 3'h3;
              end
            default:
                _13_ = current_state;
          endcase
        end
      3'h3:
        begin
          _11_ = 3'h4;
        end
      3'h4:
        begin
          _11_ = _14_;
          casez (cordic_done)
            1'h1:
              begin
                _14_ = 3'h5;
              end
            default:
                _14_ = current_state;
          endcase
        end
      3'h5:
        begin
          _11_ = 3'h0;
        end
      default:
        begin
          _11_ = 3'h0;
        end
    endcase
  end
  always @* begin
      next_state <= _06_;
  end
  always @* begin
    _08_ = result_x;
    _09_ = result_y;
    _04_ = done;
    _07_ = ready;
    _05_ = k_reg;
    _10_ = vdc_start;
    _02_ = cordic_start;
    _00_ = angle_reg;
    _01_ = cordic_angle;
    casez (_16_)
      1'h1:
        begin
          _05_ = 32'd0;
          _10_ = 1'h0;
          _02_ = 1'h0;
          _00_ = 32'd0;
          _01_ = 16'h0000;
          _08_ = 32'd0;
          _09_ = 32'd0;
          _04_ = 1'h0;
          _07_ = 1'h1;
        end
      default:
          casez (current_state)
            3'h0:
              begin
                _07_ = 1'h1;
                _04_ = 1'h0;
                _10_ = 1'h0;
                _02_ = 1'h0;
                casez (start)
                  1'h1:
                    begin
                      _07_ = 1'h0;
                      _05_ = k_in;
                    end
                  default:
                      /* empty */;
                endcase
              end
            3'h1:
                _10_ = 1'h1;
            3'h2:
              begin
                _10_ = 1'h0;
                casez (vdc_done)
                  1'h1:
                    begin
                      _00_ = _18_;
                      _01_ = angle_reg[31:16];
                    end
                  default:
                      /* empty */;
                endcase
              end
            3'h3:
                _02_ = 1'h1;
            3'h4:
                _02_ = 1'h0;
            3'h5:
              begin
                _08_ = cordic_cos;
                _09_ = cordic_sin;
                _04_ = 1'h1;
              end
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk) begin
      result_x <= _08_;
      result_y <= _09_;
      done <= _04_;
      ready <= _07_;
      k_reg <= _05_;
      vdc_start <= _10_;
      cordic_start <= _02_;
      angle_reg <= _00_;
      cordic_angle <= _01_;
  end
  always @(negedge rst_n) begin
      result_x <= _08_;
      result_y <= _09_;
      done <= _04_;
      ready <= _07_;
      k_reg <= _05_;
      vdc_start <= _10_;
      cordic_start <= _02_;
      angle_reg <= _00_;
      cordic_angle <= _01_;
  end
endmodule

module cordic_trig_16bit_simple_fixed(clk, rst_n, start, angle, cosine, sine, done, ready);
  reg [31:0] _000_;
  reg [15:0] _001_;
  reg [31:0] _002_;
  reg [15:0] _003_;
  reg [31:0] _004_;
  reg [15:0] _005_;
  reg [31:0] _006_;
  reg [15:0] _007_;
  reg [31:0] _008_;
  reg [15:0] _009_;
  reg [31:0] _010_;
  reg [15:0] _011_;
  reg [31:0] _012_;
  reg [15:0] _013_;
  reg [31:0] _014_;
  reg [15:0] _015_;
  reg [31:0] _016_;
  reg [15:0] _017_;
  reg [31:0] _018_;
  reg [15:0] _019_;
  reg [31:0] _020_;
  reg [15:0] _021_;
  reg [31:0] _022_;
  reg [15:0] _023_;
  reg [31:0] _024_;
  reg [15:0] _025_;
  reg [31:0] _026_;
  reg [15:0] _027_;
  reg [31:0] _028_;
  reg [15:0] _029_;
  reg [31:0] _030_;
  reg [15:0] _031_;
  reg [15:0] _032_;
  reg [31:0] _033_;
  reg [31:0] _034_;
  reg _035_;
  reg [3:0] _036_;
  reg [1:0] _037_;
  reg _038_;
  reg [15:0] _039_;
  reg [31:0] _040_;
  reg [31:0] _041_;
  reg [1:0] _042_;
  reg [16:0] _043_;
  reg [31:0] _044_;
  reg [16:0] _045_;
  reg [31:0] _046_;
  reg [15:0] _047_;
  reg [31:0] _048_;
  reg [1:0] _049_;
  reg [15:0] _050_;
  reg [31:0] _051_;
  reg [31:0] _052_;
  reg [31:0] _053_;
  reg [31:0] _054_;
  reg [1:0] _055_;
  reg [15:0] _056_;
  reg [31:0] _057_;
  reg [31:0] _058_;
  reg [31:0] _059_;
  reg [31:0] _060_;
  reg [1:0] _061_;
  reg [15:0] _062_;
  reg [31:0] _063_;
  reg [31:0] _064_;
  reg [15:0] _065_;
  reg [31:0] _066_;
  reg [31:0] _067_;
  reg [15:0] _068_;
  reg [31:0] _069_;
  reg [15:0] _070_;
  wire [16:0] _071_;
  wire [15:0] _072_;
  wire [16:0] _073_;
  wire [31:0] _074_;
  wire [31:0] _075_;
  wire [31:0] _076_;
  wire [31:0] _077_;
  wire [31:0] _078_;
  wire [31:0] _079_;
  wire [31:0] _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [15:0] _090_;
  wire [15:0] _091_;
  reg [31:0] _092_;
  reg [15:0] _093_;
  reg [31:0] _094_;
  reg [15:0] _095_;
  reg [31:0] _096_;
  reg [15:0] _097_;
  reg [31:0] _098_;
  reg [15:0] _099_;
  reg [31:0] _100_;
  reg [15:0] _101_;
  reg [31:0] _102_;
  reg [15:0] _103_;
  reg [31:0] _104_;
  reg [15:0] _105_;
  reg [31:0] _106_;
  reg [15:0] _107_;
  reg [31:0] _108_;
  reg [15:0] _109_;
  reg [31:0] _110_;
  reg [15:0] _111_;
  reg [31:0] _112_;
  reg [15:0] _113_;
  reg [31:0] _114_;
  reg [15:0] _115_;
  reg [31:0] _116_;
  reg [15:0] _117_;
  reg [31:0] _118_;
  reg [15:0] _119_;
  reg [31:0] _120_;
  reg [15:0] _121_;
  reg [31:0] _122_;
  reg [15:0] _123_;
  wire [31:0] _124_;
  wire [31:0] _125_;
  wire [31:0] _126_;
  wire [31:0] _127_;
  wire [31:0] _128_;
  wire [31:0] _129_;
  wire [31:0] _130_;
  wire [31:0] _131_;
  wire [31:0] _132_;
  wire [31:0] _133_;
  wire [16:0] _134_;
  wire [16:0] _135_;
  wire [16:0] _136_;
  wire [16:0] _137_;
  wire [15:0] _138_;
  wire [15:0] _139_;
  wire [15:0] _140_;
  wire [16:0] _141_;
  wire [16:0] _142_;
  wire [15:0] _143_;
  input [15:0] angle;
  reg [15:0] angle_reg;
  input clk;
  reg [31:0] cos_result;
  output [31:0] cosine;
  reg [31:0] cosine;
  output done;
  reg done;
  wire [31:0] i;
  reg [3:0] iteration;
  reg [1:0] next_state;
  output ready;
  reg ready;
  reg [15:0] reduced_angle;
  input rst_n;
  reg [31:0] sin_result;
  output [31:0] sine;
  reg [31:0] sine;
  input start;
  reg [1:0] state;
  reg [16:0] x;
  reg [31:0] x_scaled;
  reg [16:0] y;
  reg [31:0] y_scaled;
  reg [15:0] z;
  reg [15:0] atan_table [15:0];
  assign _071_ = x + _134_;
  assign _072_ = z + _090_;
  assign _073_ = y + _137_;
  assign _074_ = iteration + 32'd1;
  assign _075_ = { x[15:0], 16'h0000 } + _128_;
  assign _076_ = _075_ + _129_;
  assign _077_ = _076_ + _130_;
  assign _078_ = { y[15:0], 16'h0000 } + _131_;
  assign _079_ = _078_ + _132_;
  assign _080_ = _079_ + _133_;
  assign _081_ = iteration == 32'd15;
  assign _082_ = ! rst_n;
  assign _083_ = ! rst_n;
  assign _084_ = angle < 32'd16384;
  assign _085_ = angle < 32'd32768;
  assign _086_ = angle < 32'd49152;
  assign _087_ = angle_reg < 32'd16384;
  assign _088_ = angle_reg < 32'd32768;
  assign _089_ = angle_reg < 32'd49152;
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd134),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _163_ (
    .ADDR(_092_),
    .DATA(_093_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd135),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _164_ (
    .ADDR(_094_),
    .DATA(_095_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd136),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _165_ (
    .ADDR(_096_),
    .DATA(_097_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd137),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _166_ (
    .ADDR(_098_),
    .DATA(_099_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd138),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _167_ (
    .ADDR(_100_),
    .DATA(_101_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd139),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _168_ (
    .ADDR(_102_),
    .DATA(_103_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd140),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _169_ (
    .ADDR(_104_),
    .DATA(_105_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd141),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _170_ (
    .ADDR(_106_),
    .DATA(_107_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd142),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _171_ (
    .ADDR(_108_),
    .DATA(_109_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd143),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _172_ (
    .ADDR(_110_),
    .DATA(_111_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd144),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _173_ (
    .ADDR(_112_),
    .DATA(_113_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd145),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _174_ (
    .ADDR(_114_),
    .DATA(_115_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd146),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _175_ (
    .ADDR(_116_),
    .DATA(_117_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd147),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _176_ (
    .ADDR(_118_),
    .DATA(_119_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd148),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _177_ (
    .ADDR(_120_),
    .DATA(_121_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd149),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _178_ (
    .ADDR(_122_),
    .DATA(_123_)
  );
  \$memrd  #(
    .ABITS(32'd4),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\atan_table"),
    .TRANSPARENT(32'd0),
    .WIDTH(32'd16)
  ) _179_ (
    .ADDR(iteration),
    .CLK(1'hx),
    .DATA(_090_),
    .EN(1'hx)
  );
  \$memrd  #(
    .ABITS(32'd4),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\atan_table"),
    .TRANSPARENT(32'd0),
    .WIDTH(32'd16)
  ) _180_ (
    .ADDR(iteration),
    .CLK(1'hx),
    .DATA(_091_),
    .EN(1'hx)
  );
  assign _124_ = - _080_;
  assign _125_ = - _077_;
  assign _126_ = - _080_;
  assign _127_ = - _077_;
  assign _128_ = { x[15:0], 16'h0000 } >> $signed(32'd1);
  assign _129_ = { x[15:0], 16'h0000 } >> $signed(32'd3);
  assign _130_ = { x[15:0], 16'h0000 } >> $signed(32'd6);
  assign _131_ = { y[15:0], 16'h0000 } >> $signed(32'd1);
  assign _132_ = { y[15:0], 16'h0000 } >> $signed(32'd3);
  assign _133_ = { y[15:0], 16'h0000 } >> $signed(32'd6);
  assign _134_ = y >>> iteration;
  assign _135_ = x >>> iteration;
  assign _136_ = y >>> iteration;
  assign _137_ = x >>> iteration;
  assign _138_ = angle - 16'h4000;
  assign _139_ = angle - 16'h8000;
  assign _140_ = angle - 16'hc000;
  assign _141_ = y - _135_;
  assign _142_ = x - _136_;
  assign _143_ = z - _091_;
  always @* begin
    _035_ = done;
    _038_ = ready;
    _032_ = angle_reg;
    _034_ = cosine;
    _041_ = sine;
    _036_ = iteration;
    _043_ = x;
    _045_ = y;
    _047_ = z;
    _046_ = _053_;
    _039_ = _050_;
    _044_ = _052_;
    _033_ = _048_;
    _040_ = _051_;
    casez (_082_)
      1'h1:
        begin
          _043_ = 17'h00000;
          _045_ = 17'h00000;
          _047_ = 16'h0000;
          _036_ = 4'h0;
          _034_ = 32'd0;
          _041_ = 32'd0;
          _035_ = 1'h0;
          _038_ = 1'h1;
          _050_ = 16'h0000;
          _052_ = 32'd0;
          _053_ = 32'd0;
          _048_ = 32'd0;
          _051_ = 32'd0;
        end
      default:
        begin
          _053_ = _059_;
          _050_ = _056_;
          _052_ = _058_;
          _048_ = _054_;
          _051_ = _057_;
          casez (state)
            2'h0:
              begin
                _059_ = y_scaled;
                _058_ = x_scaled;
                _054_ = cos_result;
                _057_ = sin_result;
                _038_ = 1'h1;
                _035_ = 1'h0;
                _056_ = _062_;
                casez (start)
                  1'h1:
                    begin
                      _038_ = 1'h0;
                      _032_ = angle;
                      _062_ = _065_;
                      _047_ = _065_;
                      _036_ = 4'h0;
                      casez (_084_)
                        1'h1:
                          begin
                            _065_ = angle;
                            _043_ = 17'h09b75;
                            _045_ = 17'h00000;
                          end
                        default:
                          begin
                            _065_ = _068_;
                            casez (_085_)
                              1'h1:
                                begin
                                  _068_ = _138_;
                                  _043_ = 17'h00000;
                                  _045_ = 17'h09b75;
                                end
                              default:
                                begin
                                  _068_ = _070_;
                                  casez (_086_)
                                    1'h1:
                                      begin
                                        _070_ = _139_;
                                        _043_ = 17'h1648b;
                                        _045_ = 17'h00000;
                                      end
                                    default:
                                      begin
                                        _070_ = _140_;
                                        _043_ = 17'h00000;
                                        _045_ = 17'h1648b;
                                      end
                                  endcase
                                end
                            endcase
                          end
                      endcase
                    end
                  default:
                      _062_ = reduced_angle;
                endcase
              end
            2'h1:
              begin
                _059_ = y_scaled;
                _056_ = reduced_angle;
                _058_ = x_scaled;
                _054_ = cos_result;
                _057_ = sin_result;
                _036_ = _074_[3:0];
                casez (z[15])
                  1'h1:
                    begin
                      _043_ = _071_;
                      _045_ = _141_;
                      _047_ = _072_;
                    end
                  default:
                    begin
                      _043_ = _142_;
                      _045_ = _073_;
                      _047_ = _143_;
                    end
                endcase
              end
            2'h2:
              begin
                _056_ = reduced_angle;
                _058_ = _077_;
                _059_ = _080_;
                _054_ = _060_;
                _057_ = _063_;
                _034_ = _060_;
                _041_ = _063_;
                _035_ = 1'h1;
                casez (_087_)
                  1'h1:
                    begin
                      _060_ = _077_;
                      _063_ = _080_;
                    end
                  default:
                    begin
                      _060_ = _064_;
                      _063_ = _066_;
                      casez (_088_)
                        1'h1:
                          begin
                            _064_ = _124_;
                            _066_ = _077_;
                          end
                        default:
                          begin
                            _064_ = _067_;
                            _066_ = _069_;
                            casez (_089_)
                              1'h1:
                                begin
                                  _067_ = _125_;
                                  _069_ = _126_;
                                end
                              default:
                                begin
                                  _067_ = _080_;
                                  _069_ = _127_;
                                end
                            endcase
                          end
                      endcase
                    end
                endcase
              end
            default:
              begin
                _059_ = y_scaled;
                _056_ = reduced_angle;
                _058_ = x_scaled;
                _054_ = cos_result;
                _057_ = sin_result;
              end
          endcase
        end
    endcase
  end
  always @(posedge clk) begin
      done <= _035_;
      ready <= _038_;
      angle_reg <= _032_;
      cosine <= _034_;
      sine <= _041_;
      iteration <= _036_;
      y_scaled <= _046_;
      x <= _043_;
      y <= _045_;
      z <= _047_;
      reduced_angle <= _039_;
      x_scaled <= _044_;
      cos_result <= _033_;
      sin_result <= _040_;
  end
  always @(negedge rst_n) begin
      done <= _035_;
      ready <= _038_;
      angle_reg <= _032_;
      cosine <= _034_;
      sine <= _041_;
      iteration <= _036_;
      y_scaled <= _046_;
      x <= _043_;
      y <= _045_;
      z <= _047_;
      reduced_angle <= _039_;
      x_scaled <= _044_;
      cos_result <= _033_;
      sin_result <= _040_;
  end
  always @* begin
    _000_ = 32'd0;
    _001_ = 16'h2000;
    _002_ = 32'd1;
    _003_ = 16'h12e4;
    _004_ = 32'd2;
    _005_ = 16'h09fb;
    _006_ = 32'd3;
    _007_ = 16'h0511;
    _008_ = 32'd4;
    _009_ = 16'h028b;
    _010_ = 32'd5;
    _011_ = 16'h0146;
    _012_ = 32'd6;
    _013_ = 16'h00a3;
    _014_ = 32'd7;
    _015_ = 16'h0051;
    _016_ = 32'd8;
    _017_ = 16'h0029;
    _018_ = 32'd9;
    _019_ = 16'h0014;
    _020_ = 32'd10;
    _021_ = 16'h000a;
    _022_ = 32'd11;
    _023_ = 16'h0005;
    _024_ = 32'd12;
    _025_ = 16'h0003;
    _026_ = 32'd13;
    _027_ = 16'h0001;
    _028_ = 32'd14;
    _029_ = 16'h0001;
    _030_ = 32'd15;
    _031_ = 16'h0000;
  end
  always @* begin
      _092_ <= _000_;
      _093_ <= _001_;
      _094_ <= _002_;
      _095_ <= _003_;
      _096_ <= _004_;
      _097_ <= _005_;
      _098_ <= _006_;
      _099_ <= _007_;
      _100_ <= _008_;
      _101_ <= _009_;
      _102_ <= _010_;
      _103_ <= _011_;
      _104_ <= _012_;
      _105_ <= _013_;
      _106_ <= _014_;
      _107_ <= _015_;
      _108_ <= _016_;
      _109_ <= _017_;
      _110_ <= _018_;
      _111_ <= _019_;
      _112_ <= _020_;
      _113_ <= _021_;
      _114_ <= _022_;
      _115_ <= _023_;
      _116_ <= _024_;
      _117_ <= _025_;
      _118_ <= _026_;
      _119_ <= _027_;
      _120_ <= _028_;
      _121_ <= _029_;
      _122_ <= _030_;
      _123_ <= _031_;
  end
  initial begin
  end
  always @* begin
    _042_ = state;
    casez (_083_)
      1'h1:
          _042_ = 2'h0;
      default:
          _042_ = next_state;
    endcase
  end
  always @(posedge clk) begin
      state <= _042_;
  end
  always @(negedge rst_n) begin
      state <= _042_;
  end
  always @* begin
    _037_ = _049_;
    casez (state)
      2'h0:
        begin
          _049_ = _055_;
          casez (start)
            1'h1:
              begin
                _055_ = 2'h1;
              end
            default:
                _055_ = state;
          endcase
        end
      2'h1:
        begin
          _049_ = _061_;
          casez (_081_)
            1'h1:
              begin
                _061_ = 2'h2;
              end
            default:
                _061_ = state;
          endcase
        end
      2'h2:
        begin
          _049_ = 2'h0;
        end
      default:
          _049_ = state;
    endcase
  end
  always @* begin
      next_state <= _037_;
  end
endmodule

module div_mod_3(n, quotient, remainder);
  wire [6:0] _00_;
  wire [5:0] _01_;
  wire [4:0] _02_;
  wire [1:0] _03_;
  wire [7:0] _04_;
  wire [7:0] _05_;
  wire [7:0] _06_;
  wire [31:0] _07_;
  wire _08_;
  wire _09_;
  wire [31:0] _10_;
  wire [31:0] _11_;
  wire [1:0] _12_;
  input [7:0] n;
  wire [5:0] q1;
  wire [4:0] q2;
  wire [3:0] q3;
  wire [1:0] q4;
  output [7:0] quotient;
  wire [7:0] quotient_sum;
  wire [1:0] r1;
  wire [1:0] r2;
  wire [1:0] r3;
  wire [1:0] r4;
  wire [6:0] rem1;
  wire [5:0] rem2;
  wire [4:0] rem3;
  wire [1:0] rem4;
  output [1:0] remainder;
  assign _00_ = q1 + r1;
  assign _01_ = q2 + r2;
  assign _02_ = q3 + r3;
  assign _03_ = q4 + r4;
  assign _04_ = q1 + q2;
  assign _05_ = _04_ + q3;
  assign _06_ = _05_ + q4;
  assign _07_ = quotient_sum + 32'd1;
  assign _08_ = rem4 == 2'h3;
  assign _09_ = rem4 == 2'h3;
  assign _10_ = + quotient_sum;
  assign _11_ = _08_ ? _07_ : _10_;
  assign _12_ = _09_ ? 2'h0 : rem4;
  assign q1 = n[7:2];
  assign r1 = n[1:0];
  assign rem1 = _00_;
  assign q2 = rem1[6:2];
  assign r2 = rem1[1:0];
  assign rem2 = _01_;
  assign q3 = rem2[5:2];
  assign r3 = rem2[1:0];
  assign rem3 = _02_;
  assign q4 = rem3[3:2];
  assign r4 = rem3[1:0];
  assign rem4 = _03_;
  assign quotient_sum = _06_;
  assign quotient = _11_[7:0];
  assign remainder = _12_;
endmodule

module div_mod_7(n, quotient, remainder);
  wire [6:0] _00_;
  wire [4:0] _01_;
  wire [2:0] _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  wire [31:0] _05_;
  wire _06_;
  wire _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  wire [2:0] _10_;
  input [8:0] n;
  wire [5:0] q1;
  wire [3:0] q2;
  wire [1:0] q3;
  output [8:0] quotient;
  wire [7:0] quotient_sum;
  wire [2:0] r1;
  wire [2:0] r2;
  wire [2:0] r3;
  wire [6:0] rem1;
  wire [4:0] rem2;
  wire [2:0] rem3;
  output [2:0] remainder;
  assign _00_ = q1 + r1;
  assign _01_ = q2 + r2;
  assign _02_ = q3 + r3;
  assign _03_ = q1 + q2;
  assign _04_ = _03_ + q3;
  assign _05_ = quotient_sum + 32'd1;
  assign _06_ = rem3 == 3'h7;
  assign _07_ = rem3 == 3'h7;
  assign _08_ = + quotient_sum;
  assign _09_ = _06_ ? _05_ : _08_;
  assign _10_ = _07_ ? 3'h0 : rem3;
  assign q1 = n[8:3];
  assign r1 = n[2:0];
  assign rem1 = _00_;
  assign q2 = rem1[6:3];
  assign r2 = rem1[2:0];
  assign rem2 = _01_;
  assign q3 = rem2[4:3];
  assign r3 = rem2[2:0];
  assign rem3 = _02_;
  assign quotient_sum = _04_;
  assign quotient = _09_[8:0];
  assign remainder = _10_;
endmodule

module sphere_fsm_32bit_simple(clk, rst_n, start, k_in, base_sel0, base_sel1, result_x, result_y, result_z, done, ready);
  reg [31:0] _00_;
  reg [31:0] _01_;
  reg [63:0] _02_;
  reg [63:0] _03_;
  reg [31:0] _04_;
  reg [31:0] _05_;
  reg [31:0] _06_;
  reg _07_;
  reg [31:0] _08_;
  reg [31:0] _09_;
  reg [31:0] _10_;
  reg [63:0] _11_;
  reg [3:0] _12_;
  reg _13_;
  reg [31:0] _14_;
  reg [3:0] _15_;
  reg [31:0] _16_;
  reg _17_;
  reg [31:0] _18_;
  reg [31:0] _19_;
  reg [31:0] _20_;
  reg [31:0] _21_;
  reg _22_;
  reg [31:0] _23_;
  reg [31:0] _24_;
  reg [63:0] _25_;
  reg [63:0] _26_;
  reg [31:0] _27_;
  reg [31:0] _28_;
  reg [31:0] _29_;
  reg [63:0] _30_;
  reg [3:0] _31_;
  reg [31:0] _32_;
  reg [31:0] _33_;
  reg [31:0] _34_;
  reg [63:0] _35_;
  reg [63:0] _36_;
  reg [31:0] _37_;
  reg [31:0] _38_;
  reg [31:0] _39_;
  reg [63:0] _40_;
  reg [3:0] _41_;
  reg [31:0] _42_;
  reg [63:0] _43_;
  reg [63:0] _44_;
  reg [31:0] _45_;
  reg [31:0] _46_;
  reg [3:0] _47_;
  reg [3:0] _48_;
  wire [31:0] _49_;
  wire [31:0] _50_;
  wire [31:0] _51_;
  wire [63:0] _52_;
  wire [63:0] _53_;
  reg [31:0] _54_;
  reg [31:0] _55_;
  reg [63:0] _56_;
  reg [63:0] _57_;
  reg [31:0] _58_;
  reg [31:0] _59_;
  reg [31:0] _60_;
  wire _61_;
  wire _62_;
  wire [63:0] _63_;
  wire [31:0] _64_;
  wire [31:0] _65_;
  wire _66_;
  wire _67_;
  wire [63:0] _68_;
  wire [63:0] _69_;
  wire [31:0] _70_;
  wire [31:0] _71_;
  wire [31:0] _72_;
  wire [63:0] _73_;
  wire [31:0] _74_;
  wire [31:0] _75_;
  wire [31:0] _76_;
  wire [63:0] _77_;
  input [1:0] base_sel0;
  input [1:0] base_sel1;
  wire circle_done;
  wire circle_ready;
  wire [31:0] circle_result_x;
  wire [31:0] circle_result_y;
  reg circle_start;
  reg [31:0] circle_x_reg;
  reg [31:0] circle_y_reg;
  input clk;
  reg [31:0] cosphi_reg;
  reg [63:0] cosphi_sq;
  reg [3:0] current_state;
  output done;
  reg done;
  input [31:0] k_in;
  reg [31:0] k_reg;
  reg [3:0] next_state;
  reg [31:0] one_minus_cosphi_sq;
  output ready;
  reg ready;
  output [31:0] result_x;
  reg [31:0] result_x;
  output [31:0] result_y;
  reg [31:0] result_y;
  output [31:0] result_z;
  reg [31:0] result_z;
  input rst_n;
  reg [31:0] sinphi_reg;
  input start;
  wire vdc_done;
  wire vdc_ready;
  wire [31:0] vdc_result;
  reg vdc_start;
  assign _49_ = _77_[31:0] + 32'd32768;
  assign _50_ = _49_ + _52_[31:0];
  assign _51_ = _45_ + _53_[31:0];
  assign _52_ = _68_ / _49_;
  assign _53_ = _69_ / _45_;
  assign _61_ = ! rst_n;
  assign _62_ = ! rst_n;
  assign _63_ = cosphi_reg * cosphi_reg;
  assign _64_ = sinphi_reg * circle_x_reg;
  assign _65_ = sinphi_reg * circle_y_reg;
  assign _66_ = _49_ != 32'd0;
  assign _67_ = _45_ != 32'd0;
  assign _68_ = _77_[31:0] << $signed(32'd16);
  assign _69_ = _77_[31:0] << $signed(32'd16);
  assign _70_ = vdc_result << $signed(32'd1);
  assign _71_ = _50_ >> $signed(32'd1);
  assign _72_ = _51_ >> $signed(32'd1);
  assign _73_ = _63_ >> $signed(32'd16);
  assign _74_ = _64_ >> $signed(32'd16);
  assign _75_ = _65_ >> $signed(32'd16);
  assign _76_ = _70_ - 32'd65536;
  assign _77_ = 32'd65536 - _73_;
  circle_fsm_32bit_simple_fixed circle_inst (
    .base_sel(base_sel1),
    .clk(clk),
    .done(circle_done),
    .k_in(k_reg),
    .ready(circle_ready),
    .result_x(circle_result_x),
    .result_y(circle_result_y),
    .rst_n(rst_n),
    .start(circle_start)
  );
  vdcorput_fsm_32bit_simple vdc_inst (
    .base_sel(base_sel0),
    .clk(clk),
    .done(vdc_done),
    .k_in(k_reg),
    .ready(vdc_ready),
    .result(vdc_result),
    .rst_n(rst_n),
    .start(vdc_start)
  );
  always @* begin
    _12_ = current_state;
    casez (_61_)
      1'h1:
          _12_ = 4'h0;
      default:
          _12_ = next_state;
    endcase
  end
  always @(posedge clk) begin
      current_state <= _12_;
  end
  always @(negedge rst_n) begin
      current_state <= _12_;
  end
  always @* begin
    _15_ = _31_;
    casez (current_state)
      4'h0:
        begin
          _31_ = _41_;
          casez (start)
            1'h1:
              begin
                _41_ = 4'h1;
              end
            default:
                _41_ = current_state;
          endcase
        end
      4'h1:
        begin
          _31_ = 4'h2;
        end
      4'h2:
        begin
          _31_ = _47_;
          casez (vdc_done)
            1'h1:
              begin
                _47_ = 4'h3;
              end
            default:
                _47_ = current_state;
          endcase
        end
      4'h3:
        begin
          _31_ = 4'h4;
        end
      4'h4:
        begin
          _31_ = _48_;
          casez (circle_done)
            1'h1:
              begin
                _48_ = 4'h5;
              end
            default:
                _48_ = current_state;
          endcase
        end
      4'h5:
        begin
          _31_ = 4'h6;
        end
      4'h6:
        begin
          _31_ = 4'h7;
        end
      4'h7:
        begin
          _31_ = 4'h0;
        end
      default:
        begin
          _31_ = 4'h0;
        end
    endcase
  end
  always @* begin
      next_state <= _15_;
  end
  always @* begin
    _18_ = result_x;
    _19_ = result_y;
    _20_ = result_z;
    _13_ = done;
    _17_ = ready;
    _14_ = k_reg;
    _10_ = cosphi_reg;
    _21_ = sinphi_reg;
    _08_ = circle_x_reg;
    _09_ = circle_y_reg;
    _22_ = vdc_start;
    _07_ = circle_start;
    _11_ = _30_;
    _16_ = _32_;
    _00_ = _23_;
    _01_ = _24_;
    _04_ = _27_;
    _05_ = _28_;
    _06_ = _29_;
    _02_ = _25_;
    _03_ = _26_;
    casez (_62_)
      1'h1:
        begin
          _30_ = cosphi_sq;
          _32_ = one_minus_cosphi_sq;
          _23_ = _54_;
          _24_ = _55_;
          _27_ = _58_;
          _28_ = _59_;
          _29_ = _60_;
          _25_ = _56_;
          _26_ = _57_;
          _14_ = 32'd0;
          _10_ = 32'd0;
          _21_ = 32'd0;
          _08_ = 32'd0;
          _09_ = 32'd0;
          _18_ = 32'd0;
          _19_ = 32'd0;
          _20_ = 32'd0;
          _13_ = 1'h0;
          _17_ = 1'h1;
          _22_ = 1'h0;
          _07_ = 1'h0;
        end
      default:
        begin
          _30_ = _40_;
          _32_ = _42_;
          _23_ = _33_;
          _24_ = _34_;
          _27_ = _37_;
          _28_ = _38_;
          _29_ = _39_;
          _25_ = _35_;
          _26_ = _36_;
          casez (current_state)
            4'h0:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
                _17_ = 1'h1;
                _13_ = 1'h0;
                casez (start)
                  1'h1:
                    begin
                      _17_ = 1'h0;
                      _14_ = k_in;
                    end
                  default:
                      /* empty */;
                endcase
              end
            4'h1:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
                _22_ = 1'h1;
              end
            4'h2:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
                _22_ = 1'h0;
                casez (vdc_done)
                  1'h1:
                      _10_ = _76_;
                  default:
                      /* empty */;
                endcase
              end
            4'h3:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
                _07_ = 1'h1;
              end
            4'h4:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
                _07_ = 1'h0;
                casez (circle_done)
                  1'h1:
                    begin
                      _08_ = circle_result_x;
                      _09_ = circle_result_y;
                    end
                  default:
                      /* empty */;
                endcase
              end
            4'h5:
              begin
                _40_ = _63_;
                _42_ = _77_[31:0];
                _34_ = _77_[31:0];
                _37_ = _49_;
                _38_ = _45_;
                _35_ = _43_;
                _39_ = _46_;
                _36_ = _44_;
                _33_ = _46_;
                _21_ = _46_;
                casez (_66_)
                  1'h1:
                    begin
                      _43_ = _52_;
                      _45_ = _71_;
                    end
                  default:
                    begin
                      _43_ = _56_;
                      _45_ = 32'd0;
                    end
                endcase
                casez (_67_)
                  1'h1:
                    begin
                      _44_ = _53_;
                      _46_ = _72_;
                    end
                  default:
                    begin
                      _44_ = _57_;
                      _46_ = 32'd0;
                    end
                endcase
              end
            4'h6:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
                _18_ = _74_;
                _19_ = _75_;
                _20_ = cosphi_reg;
              end
            4'h7:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
                _13_ = 1'h1;
              end
            default:
              begin
                _40_ = cosphi_sq;
                _42_ = one_minus_cosphi_sq;
                _33_ = _54_;
                _34_ = _55_;
                _37_ = _58_;
                _38_ = _59_;
                _39_ = _60_;
                _35_ = _56_;
                _36_ = _57_;
              end
          endcase
        end
    endcase
  end
  always @(posedge clk) begin
      result_x <= _18_;
      result_y <= _19_;
      result_z <= _20_;
      done <= _13_;
      ready <= _17_;
      k_reg <= _14_;
      cosphi_reg <= _10_;
      sinphi_reg <= _21_;
      circle_x_reg <= _08_;
      circle_y_reg <= _09_;
      cosphi_sq <= _11_;
      one_minus_cosphi_sq <= _16_;
      vdc_start <= _22_;
      circle_start <= _07_;
      _54_ <= 32'hxxxxxxxx;
      _55_ <= 32'hxxxxxxxx;
      _58_ <= 32'hxxxxxxxx;
      _59_ <= 32'hxxxxxxxx;
      _60_ <= 32'hxxxxxxxx;
      _56_ <= 64'hxxxxxxxxxxxxxxxx;
      _57_ <= 64'hxxxxxxxxxxxxxxxx;
  end
  always @(negedge rst_n) begin
      result_x <= _18_;
      result_y <= _19_;
      result_z <= _20_;
      done <= _13_;
      ready <= _17_;
      k_reg <= _14_;
      cosphi_reg <= _10_;
      sinphi_reg <= _21_;
      circle_x_reg <= _08_;
      circle_y_reg <= _09_;
      cosphi_sq <= _11_;
      one_minus_cosphi_sq <= _16_;
      vdc_start <= _22_;
      circle_start <= _07_;
      _54_ <= 32'hxxxxxxxx;
      _55_ <= 32'hxxxxxxxx;
      _58_ <= 32'hxxxxxxxx;
      _59_ <= 32'hxxxxxxxx;
      _60_ <= 32'hxxxxxxxx;
      _56_ <= 64'hxxxxxxxxxxxxxxxx;
      _57_ <= 64'hxxxxxxxxxxxxxxxx;
  end
endmodule

module vdcorput_fsm_32bit_simple(clk, rst_n, start, k_in, base_sel, result, done, ready);
  reg [31:0] _00_;
  reg [31:0] _01_;
  reg [2:0] _02_;
  reg _03_;
  reg [31:0] _04_;
  reg [2:0] _05_;
  reg [31:0] _06_;
  reg [31:0] _07_;
  reg _08_;
  reg [31:0] _09_;
  reg [31:0] _10_;
  reg [2:0] _11_;
  reg [2:0] _12_;
  reg [2:0] _13_;
  wire [31:0] _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [31:0] _18_;
  wire [31:0] _19_;
  wire [31:0] _20_;
  wire _21_;
  wire [31:0] _22_;
  wire [31:0] _23_;
  wire [31:0] _24_;
  wire [31:0] _25_;
  reg [31:0] acc_reg;
  reg [31:0] base_reg;
  input [1:0] base_sel;
  input clk;
  reg [2:0] current_state;
  wire [7:0] div3_quotient;
  wire [1:0] div3_remainder;
  wire [8:0] div7_quotient;
  wire [2:0] div7_remainder;
  output done;
  reg done;
  input [31:0] k_in;
  reg [31:0] k_reg;
  reg [2:0] next_state;
  reg [31:0] power_reg;
  reg [31:0] quotient_reg;
  output ready;
  reg ready;
  reg [31:0] remainder_reg;
  output [31:0] result;
  reg [31:0] result;
  input rst_n;
  input start;
  assign _14_ = acc_reg + _18_;
  assign _15_ = k_reg == 32'd0;
  assign _16_ = ! rst_n;
  assign _17_ = ! rst_n;
  assign _18_ = remainder_reg * power_reg;
  assign _19_ = power_reg * 32'd21845;
  assign _20_ = power_reg * 32'd9362;
  assign _21_ = remainder_reg != 32'd0;
  assign _22_ = k_reg >> $signed(32'd1);
  assign _23_ = power_reg >> $signed(32'd1);
  assign _24_ = _19_ >> $signed(32'd16);
  assign _25_ = _20_ >> $signed(32'd16);
  div_mod_3 div3_inst (
    .n(k_reg[7:0]),
    .quotient(div3_quotient),
    .remainder(div3_remainder)
  );
  div_mod_7 div7_inst (
    .n(k_reg[8:0]),
    .quotient(div7_quotient),
    .remainder(div7_remainder)
  );
  always @* begin
    _02_ = current_state;
    casez (_16_)
      1'h1:
          _02_ = 3'h0;
      default:
          _02_ = next_state;
    endcase
  end
  always @(posedge clk) begin
      current_state <= _02_;
  end
  always @(negedge rst_n) begin
      current_state <= _02_;
  end
  always @* begin
    _05_ = _11_;
    casez (current_state)
      3'h0:
        begin
          _11_ = _12_;
          casez (start)
            1'h1:
              begin
                _12_ = 3'h1;
              end
            default:
                _12_ = current_state;
          endcase
        end
      3'h1:
        begin
          _11_ = 3'h2;
        end
      3'h2:
        begin
          _11_ = 3'h3;
        end
      3'h3:
        begin
          _11_ = 3'h4;
        end
      3'h4:
        begin
          _11_ = 3'h5;
        end
      3'h5:
        begin
          _11_ = _13_;
          casez (_15_)
            1'h1:
              begin
                _13_ = 3'h6;
              end
            default:
              begin
                _13_ = 3'h2;
              end
          endcase
        end
      3'h6:
        begin
          _11_ = 3'h0;
        end
      default:
        begin
          _11_ = 3'h0;
        end
    endcase
  end
  always @* begin
      next_state <= _05_;
  end
  always @* begin
    _03_ = done;
    _08_ = ready;
    _04_ = k_reg;
    _10_ = result;
    _06_ = power_reg;
    _00_ = acc_reg;
    _01_ = base_reg;
    _09_ = remainder_reg;
    _07_ = quotient_reg;
    casez (_17_)
      1'h1:
        begin
          _04_ = 32'd0;
          _06_ = 32'd65536;
          _00_ = 32'd0;
          _01_ = 32'd2;
          _09_ = 32'd0;
          _07_ = 32'd0;
          _10_ = 32'd0;
          _03_ = 1'h0;
          _08_ = 1'h1;
        end
      default:
          casez (current_state)
            3'h0:
              begin
                _08_ = 1'h1;
                _03_ = 1'h0;
                casez (start)
                  1'h1:
                    begin
                      _08_ = 1'h0;
                      _04_ = k_in;
                    end
                  default:
                      /* empty */;
                endcase
              end
            3'h1:
              begin
                _00_ = 32'd0;
                casez (base_sel)
                  2'h0:
                    begin
                      _01_ = 32'd2;
                      _06_ = 32'd32768;
                    end
                  2'h1:
                    begin
                      _01_ = 32'd3;
                      _06_ = 32'd21845;
                    end
                  2'h2:
                    begin
                      _01_ = 32'd7;
                      _06_ = 32'd9362;
                    end
                  default:
                    begin
                      _01_ = 32'd2;
                      _06_ = 32'd32768;
                    end
                endcase
              end
            3'h2:
                casez (base_reg)
                  32'd2:
                    begin
                      _07_ = _22_;
                      _09_ = { 31'h00000000, k_reg[0] };
                    end
                  32'd3:
                    begin
                      _07_ = { 24'h000000, div3_quotient };
                      _09_ = { 30'h00000000, div3_remainder };
                    end
                  32'd7:
                    begin
                      _07_ = { 23'h000000, div7_quotient };
                      _09_ = { 29'h00000000, div7_remainder };
                    end
                  default:
                    begin
                      _07_ = 32'd0;
                      _09_ = 32'd0;
                    end
                endcase
            3'h3:
                casez (_21_)
                  1'h1:
                      _00_ = _14_;
                  default:
                      /* empty */;
                endcase
            3'h4:
              begin
                _04_ = quotient_reg;
                casez (base_reg)
                  32'd2:
                      _06_ = _23_;
                  32'd3:
                      _06_ = _24_;
                  32'd7:
                      _06_ = _25_;
                  default:
                      /* empty */;
                endcase
              end
            3'h5:
                /* empty */;
            3'h6:
              begin
                _10_ = acc_reg;
                _03_ = 1'h1;
              end
            default:
                /* empty */;
          endcase
    endcase
  end
  always @(posedge clk) begin
      done <= _03_;
      ready <= _08_;
      k_reg <= _04_;
      result <= _10_;
      power_reg <= _06_;
      acc_reg <= _00_;
      base_reg <= _01_;
      remainder_reg <= _09_;
      quotient_reg <= _07_;
  end
  always @(negedge rst_n) begin
      done <= _03_;
      ready <= _08_;
      k_reg <= _04_;
      result <= _10_;
      power_reg <= _06_;
      acc_reg <= _00_;
      base_reg <= _01_;
      remainder_reg <= _09_;
      quotient_reg <= _07_;
  end
endmodule
